### ISSUE TITLE
Minor issues with the tutorials

### ISSUE THREAD

**Issue by mythreyiramesh** [Wikunia/Javis.jl#114]
This is a list of a few minor issues with the tutorials that I could spot:

# Tutorial 1
1. Snippet for adding second ball: missing parenthesis. Should be:
```
...
Action(1:70, :blue_ball, (args...)->object(Point(100,80), "blue"))
...
```
2. Some of the initial snippets declare `myvideo = Video(500, 500)` but later on, `video` is used instead.

# Tutorial 2
1. The snippet for adding the gridlines must include the closing parenthesis for the last `Action()`.
2. The snippet for adding electrodes skips over the declaration of `radius = 15`.
3. The snippet for adding random colours must have `rand(indicators, length(electrode_locations)),` instead of `rand(indicators),`. The surrounding explanation must also be modified.

# Tutorial 3
1. The [documentation](https://wikunia.github.io/Javis.jl/dev/#Optional-Dependencies) mentions the dependency on MathJax but not the dependency on `LateXStrings.jl`.
2. Typo in the LaTeX string example: missing closing quotes. Should be:
```
my_latex_string = L"9\frac{3}{4}"
```
3. The first snippet for rendering LaTeX passes `video.width / -2, video.height / -2` to `latex()`, but it should be replaced by `translate(video.width / -2, video.height / -2)` instead. The surrounding explanation must also be modified.

# Tutorial 4
1. It's not clearly mentioned that `javis()` is called from `face()`. Adding a call to `face()` at the end of the full code might also be needed.

**Comment by TheCedarPrince** [comment]
Hey @mythreyiramesh 

Thank you kindly for the bug report! I've incorporated all the fixes and am closing this issue. Also, I have acknowledged you in our README.md. Thanks for helping make Javis.jl even better! ~tcp

**Comment by Wikunia** [comment]
I would like to keep this open until the PR is merged.
