### ISSUE TITLE
Add Support AbstractPaths for pathname argument

### ISSUE THREAD

**Issue by jordancluts** [Wikunia/Javis.jl#116]
**Is your feature request related to a problem? Please explain.**
Filepaths.jl and Filepathsbase.jl provide a type based approach to file paths. Makes programmatic usage much easier. It'd be great to support that interface.

**Describe the solution you'd like**
Support AbstractPath Types

**Describe alternatives you've considered**
This is a feature enhancement that would be nice to have and likely not take too much work, but ultimately the currently standard string-based path API does get the job done.

**Comment by Wikunia** [comment]
Thanks for opening the issue @jordancluts . I do think that this is likely to be an issue in those libraries which can be fixed inside Javis but maybe it would make sense to mention them there.

What I mean is the following:

`pathname = p"gifs/test.gif"` is what I assume you want to have. Is that correct?

When I write `"Pathname: $pathname"` this works but inside the run command i.e 
```
run(`ffmpeg .... $pathname`)
```

this gets messed up and the slashes are lost.

I figured that we can use `string(pathname)` instead but I think it should be done by the libraries as this is unexpected behavior.

**Comment by jordancluts** [comment]
Thanks for your thoughts @Wikunia. Which libraries are you referring to that would need fixed? Do you mean Javis dependencies which could be modified to accept both string and filepath types?

**Comment by Wikunia** [comment]
I think that `FilePathsBase` should handle this. I will provide a fix tomorrow that makes it work but maybe it should still be an issue in their repo that when interpolating it inside backticks it seems to remove slashes which is unexpected.

In general Javis does not need a new dependency for this as we just handle it as a string. The library itself should interpolate it into a string in my understanding at least. I hope that makes more sense. I can also investigate it further tmr and open the issue on their end. 

If you open an issue on either of those repos please link to this issue and/or ping me such that I'm aware :wink:

**Comment by jordancluts** [comment]
Ah I see what you mean now. Sorry for not grasping the first time around. Having glanced at the Javis code it does seem like there is nothing that would need to be changed to support it in a future world where interpolating into a command string works as expected. Certainly no need for a dependency.
