### ISSUE TITLE
Improve Instructions on Testing

### ISSUE THREAD

**Issue by TheCedarPrince** [Wikunia/Javis.jl#118]
Based on #112 , the testing methodology is out of date in `contributing.md`. This needs to be updated!

**Comment by Wikunia** [comment]
Can you clarify which part is out of date?

**Comment by TheCedarPrince** [comment]
So, that was a misnomer. The testing methodology is still correct, but I wanted to add more info on how we are doing testing using the Project.toml in the `test` directory now. So, therefore, if a test dependency needed to be added, I wanted to include the correct instructions on how to do that.

**Comment by Wikunia** [comment]
Ah okay got you. The testing procedure is still the same though but yeah for contributing that might be helpful.

**Comment by TheCedarPrince** [comment]
Add information about needing JuliaFormatter for PRs! Update PR requirements for now.
