### ISSUE TITLE
Tutorial: Animations.jl

### ISSUE THREAD

**Issue by Wikunia** [Wikunia/Javis.jl#135]
We need another tutorial or some kind of documentation for #125 once that is finished.

**Comment by Wikunia** [comment]
Shall I write one as you might be busy with the live viewer and the scaling tutorial @TheCedarPrince ?

**Comment by TheCedarPrince** [comment]
If you could, that would be great @Wikunia ! Perhaps basing your tutorial off of your blog on Animations.jl would be a good place to start! Also, the Perlin noise example might be cool as well! Maybe you could have both those animations here?

Also, if you don't want to write the whole thing but provide most of the code and content, I can go back through later and work some of my magic on it. :sparkles:
