### ISSUE TITLE
Can it do convolutional filter animations?

### ISSUE THREAD

**Issue by xiaodaigh** [Wikunia/Javis.jl#140]
![image](https://camo.githubusercontent.com/f0f0171eac4a2ed541ca8bf79e1c2eccb8d8b61b/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f69344e6a4177797467495244572f67697068792e676966
)

Make it look exactly as above?

**Comment by TheCedarPrince** [comment]
Hey @xiaodaigh,

This is a great idea that would be able to be implemented right now using Javis. What we have been thinking is making other repositories that are built on top of Javis that can offer domain specific functionality. Feel free to begin work on something like `JavisML` or something that could be specific for ML utilizing Javis. You could ping me if you want if you start building something! 

Most likely, we will not want to create this as a functionality for the core Javis repository. Therefore, we will probably close this issue - what do you think @Wikunia ?

**Comment by xiaodaigh** [comment]
i see. if anything, i will just make a gist instead of a package. can close and if anyone makes one using javis can just post the code here.

**Comment by TheCedarPrince** [comment]
Sounds great! Would love to see a gist some day @xiaodaigh!

**Comment by xiaodaigh** [comment]
need to wait for this PR right? https://github.com/Wikunia/Javis.jl/pull/162

**Comment by TheCedarPrince** [comment]
Actually, no - let's chat about this over on Zulip @xiaodaigh
