### ISSUE TITLE
Easy Way to Return Current Scale of Object

### ISSUE THREAD

**Issue by TheCedarPrince** [Wikunia/Javis.jl#156]
**Is your feature request related to a problem? Please explain.**

Currently, it is not intuitive to retrieve the current scale of an object. One has to use the current method of `val(:_current_scale)` to gain access to the current scaling value of an object. This is not very user friendly at the moment. 

**Describe the solution you'd like**
Perhaps we could somehow define a new struct that is associated with each new drawn shape or object. Maybe have the struct be optionally created for only when you want to capture relevant information about a particular object? I am not sure what would be the best approach currently.

**Additional context**
Currently, this method is invoked in #143 so when we get this issue figured out, we need to update that tutorial somewhat.

**Comment by Wikunia** [comment]
I don't think that we want to support this current scale at all. Normal use case would be to scale a layer and move it to a different part of the screen. If one wants to scale a text one uses fontsize, for the circle the radius is used etc.

What do you think? Also see #234

**Comment by TheCedarPrince** [comment]
I agree with you. I am going to close this issue because I think #234 rather takes care of it.
