### ISSUE TITLE
Animate transposing a matrix

### ISSUE THREAD

**Issue by Wikunia** [Wikunia/Javis.jl#16]
Came as a suggestion of @xiaodaigh during the stream today.

**Comment by Sov-trotter** [comment]
Shouldn't it be generalized to "Animate Latex elements"

**Comment by Wikunia** [comment]
We are making tiny steps 😂 but yeah in general the most general form of it is preferred.

**Comment by Wikunia** [comment]
One idea: https://upload.wikimedia.org/wikipedia/commons/e/e4/Matrix_transpose.gif

**Comment by Wikunia** [comment]
Current state using morphing:
![transpose](https://user-images.githubusercontent.com/4931746/93063923-38a37900-f677-11ea-9d28-ec39b76c47f1.gif)

**Comment by Sov-trotter** [comment]
So can we give it a bit of motion blur? xD
or maybe maybe increase the opacity of digits as we move towards the end of the animation

**Comment by Wikunia** [comment]
Not yet but if you have time today we can discuss this during a stream :joy:

**Comment by Wikunia** [comment]
The first version is merged so I'll close this. There are still quite a lot of things to do though.

**Comment by xiaodaigh** [comment]
is there example code on how to achieve this?

**Comment by TheCedarPrince** [comment]
A tutorial is on its way @xiaodaigh !
