### ISSUE TITLE
Improve Action Error Messages

### ISSUE THREAD

**Issue by TheCedarPrince** [Wikunia/Javis.jl#164]
**Is your feature request related to a problem? Please explain.**

It can be difficult to track where an error is being thrown from the javis function when multiple actions are being tied together. Currently, if there is an error in `javis` the error handler says that there is an error within `javis` but not why it is being caused.

**Describe the solution you'd like**

It would be nice if I could have a traceback such that I can locate the specific `Action` that caused an error and perhaps even what part of the `Action` failed. Going deeper, after locating the `Action`, perhaps even the `SubAction` as well.

**Describe alternatives you've considered**

Commenting can work, but only so much. I'd rather have an intelligent and intelligible error message that can tell me why I am screwing up.

**Comment by Wikunia** [comment]
I think implementing #100 will make this obsolete.
Then we would define actions outside the javis function and go the way that JuMP.jl is doing
