### ISSUE TITLE
Standardize Documentation Practices

### ISSUE THREAD

**Issue by TheCedarPrince** [Wikunia/Javis.jl#17]
## Problem 

The documentation for Javis is sparse right now and is not terribly clear in most places. Let's fix that up! I'll be implementing [BlueStyle](https://github.com/invenia/BlueStyle) in most of the areas as best is applicable.

## Places to Improve Documentation

- [ ] **LaTeXSVG** - rather confused about what this is doing (ping @Wikunia for explanation)
- [ ] **float_attribute** - needs a further explanation and definition of kwargs
- [ ] **path_move** - needs a further explanation and definition of kwargs
- [ ] **set_attr** - needs an example
- [ ] **draw_obj** - needs a further explanation and definition of kwargs
- [ ] **include** - rather confused about what this is doing (ping @Wikunia for explanation)
- [ ] **path_quadratic** - needs a further explanation and definition of kwargs
- [ ] **set_attrs** - example and what is the object `o`
- [ ] **eval** - needs a further explanation and definition of kwargs
- [x] **latex** - almost done, needs and example and explanation of actions
- [ ] **pathsvg** - almost done, just needs an example
- [ ] **set_transform** - rather confused about what this is doing (ping @Wikunia for explanation)

**Comment by Wikunia** [comment]
Thanks for the comment..as we have several PRs and this issue now about the open PR #6, we might want to try to merge that then other PRs are easier to review. Maybe you are able to add some missing documentation to it or I'll next week :)

Action is a struct that is holding information about the frames, the function it's calling as well as some transformation.

**Comment by TheCedarPrince** [comment]
Great point @Wikunia !

I am actually going to change this issue to a comprehensive issue on improving general documentation practices in the whole package ecosystem. I'll be working on improving all the documentation as best I can. If I have any questions about anything you are doing, I will ping you!

**Comment by Wikunia** [comment]
From my point of view we probably want to focus on features and documentation of functions which are exported. Nevertheless let me explain the parts you pinged me on here:

LaTeXSVG:
The general way of rendering LaTeX is a two way process. 
1. Render it with a LaTeX compiler into SVG
2. Take the svg and create the drawing
The first step is normally much slower and needs an extra program which I happened to fail to include in the testing pipeline. 
For this reason the first part is cached such that when the user wants to display an equation in several frames the first step is performed once and is then cached. In the frames afterwards the cached svg is simply drawn. 

Can you clarify what you don't understand about `include` or which include you're referring to?
The normal Julia `include` simply includes one Julia file into a different file to avoid having thousands of lines of code inside one file.

`set_transform` probably (based on me remembering 😂) transforms the canvas using rotation or translation.

**Comment by TheCedarPrince** [comment]
That's true @Wikunia! I will make that the primary focus and go back to look at which ones are being exported. I wanted to document most of the functions as for me, it is very difficult to understand what exactly is going on. However, even BlueStyle says to focus documentation on what is being exported.

Thanks for the explanations! I was referring to the `Javis.include` or is that the same as the `Base.include` function?

**Comment by Wikunia** [comment]
There is no `Javis.include`.
BTW what do you mean by `eval` ?

**Comment by Wikunia** [comment]
We should also separate exported functions from internal functions inside the documentation. Shell that be a new issue @TheCedarPrince ?

**Comment by TheCedarPrince** [comment]
@Wikunia I agree with the separation between internal/exported functions. Go ahead and create the issue and we can chat about it there.

**Comment by Wikunia** [comment]
It's already part of the PR #27

**Comment by TheCedarPrince** [comment]
I think we can close this issue as of now because we have a clearer understanding of how we are documenting internal/exported functions. Many of these functions are internal and are now documented adequately. Closing now.
