### ISSUE TITLE
Create a new gallery showcase gif

### ISSUE THREAD

**Issue by Wikunia** [Wikunia/Javis.jl#181]
For v0.2 we would like to showcase the new functionality on the Readme.

One way I can image is: instead of having a big gif as we currently have it bit be reasonable to have a table (without borders) to show the same thing but the gifs can be clickable to the tutorial where this explained or if there doesn't exist such a tutorial we can have an examples folder with a file for each animation on how to reproduce this.
This is way easier than writing a tutorial each time and should be sufficient after we explained the concepts of Javis.

What do you think @TheCedarPrince ?

**Comment by TheCedarPrince** [comment]
I really like this idea! Especially the examples idea to reduce the number of tutorials required.

**Comment by TheCedarPrince** [comment]
Here is sample markdown of what we were thinking could be done:

```mkd
| Animation                                                                                     |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------|
| ![](assets/eeg.gif)                                                                           |
| **Tutorial:** [EEG](https://wikunia.github.io/Javis.jl/stable/tutorials/tutorial_2/) |

```

Which can look something like this:

![image](https://user-images.githubusercontent.com/29561456/93524499-926ba380-f902-11ea-8aa9-e42bf2a017cb.png)
