### ISSUE TITLE
[BUG] follow_path only works from origin and if the subaction starts from 1

### ISSUE THREAD

**Issue by Wikunia** [Wikunia/Javis.jl#189]
**Before Filing a Report**

**Describe the bug**

The `follow_path` SubAction only works if the frame starts with `1`. I misused the variable `rel_frame`.
Additionally the path currently has to start at the origin to make sense. I would change this to start at the first point of the path.

**To Reproduce**

1. Julia Version (i.e. output of `julia -v`):
1.5.1

2. Operating system (Mac, Linux, Windows):
Linux

3. Minimum working code example that led to bug:

```julia
points = [Point(10, 20), Point(100, 20)]

Action(
    1:80,
    (args...) -> circle_with_color(first(points), 10, "red");
    subactions = [
        SubAction(1:20, appear(:fade)),
        SubAction(21:80, follow_path(points)),
    ],
)
```

**Expected Behavior and Actual Behavior**

I expected that it follows the path by starting at `first(points)` but instead it starts at `first(points) + first(points)`

**Comment by Wikunia** [comment]
Actually I'm not sure by the second part of this to be honest. 
Probably the current one is fine and one should call it with `follow_path(points .- first(points))`

**Comment by Wikunia** [comment]
@TheCedarPrince can you give an example of how you would do the following animation:
Let a star appear by using `:scale` and then move it along a rectangle `rect(Point(-50, 50), 100, 100))` ?
Don't actually try it out just write the code here to see what feels natural to you :wink:

**Comment by TheCedarPrince** [comment]
Ok, here would be my first attempt:

```julia

vid = Video(500, 500)

points = [Point(10, 20), Point(100, 20)]

actions = [BackgroundAction(1:80, ground),
Action(
    1:80,
    (args...) -> star(O);
    subactions = [
        SubAction(1:20, appear(:scale)),
        SubAction(21:80, follow_path(points)),
    ],
)]

javis(vid, actions, "test.gif")
```

I was somewhat confused by your question. Was this what you were looking for?

**Comment by Wikunia** [comment]
I want the star to appear at Point (10, 20)
