### ISSUE TITLE
Conditional Loading of Packages

### ISSUE THREAD

**Issue by TheCedarPrince** [Wikunia/Javis.jl#193]
**Is your feature request related to a problem? Please explain.**

I have noticed recently that `using Javis` seems to be taking much longer than it used to. I ran some benchmarks and it was somewhat concerning:

**v0.1.5 Benchmarks:**

```julia
julia> @time using Javis
 41.913861 seconds (37.30 M allocations: 2.000 GiB, 3.49% gc time)
```

**v0.1.0 Benchmarks:**

```julia
julia> @time using Javis
[ Info: Precompiling Javis [78b212ba-a7f9-42d4-b726-60726080707e]
 21.673696 seconds (12.55 M allocations: 715.007 MiB, 0.83% gc time)
```

We have currently doubled the compile time of `Javis`! :scream: 

**Describe the solution you'd like**

I would like to conditionally compile packages as they are needed. Obviously, some packages that are critical would always be loaded but I think we need to identify where the compile time issues come from.

**Describe alternatives you've considered**

Thanks to a suggestion from @mcabbott I think [`Requires.jl`](https://github.com/JuliaPackaging/Requires.jl) would help fix this problem.

**Comment by Wikunia** [comment]
Interesting idea but in that case the user would need to write `using Gtk`, right? Or cans that be avoided as well? I didn't really understand `Requires.jl` I guess

**Comment by TheCedarPrince** [comment]
From what I have read and understood about `Requires.jl`, I think having to write `using Gtk` can be avoided. I will have to research this a bit more to confirm.

**Comment by Sov-trotter** [comment]
So does it have it be something like 
```
function __init__()
    @require Gtk="4c0ca9eb-093a-5379-98c5-f87ac0bbbf44" Base.show("Gtk Loaded")
end
```

**Comment by TheCedarPrince** [comment]
That is my understanding of what Requires.jl would do here. I haven't had much time to look into this. Would you be able to experiment with this functionality to decrease the precompile time @Sov-trotter? I'd be happy to provide support you in creating a PR. 🙂

**Comment by Wikunia** [comment]
We probably want this only for the image viewer as I assume Gtk requires the most. This assumption needs to be tested :smile: .
In general I believe that precompilation time isn't super important as it should be done only once for all users (except for developers)

Thanks for your comment @Sov-trotter  and yeah if you're interested we appreciate your help :wink:

**Comment by Sov-trotter** [comment]
Sorry I should've created a PR by now but I am running into the error.
```
Gtk-Message: 13:18:56.751: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:18:56.751: Failed to load module "canberra-gtk-module"
```
I have update Gtk based on the other issues on [Gtk.jl](https://github.com/JuliaGraphics/Gtk.jl/issues/458). Almost bricked my gnome in that process. :(

**Comment by TheCedarPrince** [comment]
Hey @Sov-trotter no worries! I have had that error before on Linux-based machines. What machine are you using? If you are using a linux based machine, this solution should assist: https://askubuntu.com/questions/208431/failed-to-load-module-canberra-gtk-module

**Comment by TheCedarPrince** [comment]
Closed due to inability to solve and fix at the moment. May reopen someday!
