### ISSUE TITLE
Pluto Support and Integration

### ISSUE THREAD

**Issue by TheCedarPrince** [Wikunia/Javis.jl#208]
**Is your feature request related to a problem? Please explain.**

Currently, Javis does not work within a Pluto environment. One cannot use Javis to view frames of an animation easily like they could using the built-in Javis image viewer. Furthermore, on some platforms, the Javis image viewer is not performant due to it being built using Gtk.jl. 

We could perhaps get around this performance issue as well by providing browser-based support built around using Pluto as a platform.

**Describe the solution you'd like**

I would love to build functionality into Javis Pluto notebook support by creating something like this:

![sliderplot](https://user-images.githubusercontent.com/29561456/94599680-cc239f00-025e-11eb-9b6c-c4124f300c9f.gif)

> Source: https://blog.dominodatalab.com/interactive-dashboards-in-jupyter/

But using Pluto instead. I think this functionality could be achieved by using [PlutoUi.jl](https://github.com/fonsp/PlutoUI.jl). Furthermore, this might be better suited to go into its own repository. So, initial development may take place on the main branch but later move to its own dedicated location. 

**Describe alternatives you've considered**

The best alternative would be the Javis image viewer but since not all platforms best support GTK based GUIs, this would provide greater applicability of Javis. I am not certain how Pluto will take to what I am imagining being an image viewer; I imagine Jupyter may be more performant but I am not sure at this point. Only experimentation will tell!

**Comment by clad26** [comment]
Any update on this?

**Comment by TheCedarPrince** [comment]
Hey @clad26 - thanks for the ping!

Currently, @Sov-trotter has attempted to look into this. However, it seems like the problem, based on the [discussions here](https://julialang.zulipchat.com/#narrow/stream/243342-pluto.2Ejl/topic/Integration.20into.20a.20package) are more on Pluto side. We unfortunately do not have any control over this matter from our side.

Pinging @sov-trotter if he has anymore updates he could add.

**Comment by Sov-trotter** [comment]
https://user-images.githubusercontent.com/43717431/112513984-ddd3a280-8dba-11eb-9288-74969ab9fb61.mp4

Not a pure integration, but something that we can add in the docs

**Comment by TheCedarPrince** [comment]
That's fantastic @Sov-trotter ! Super curious on how you got this working - how did you hook into PlutoUI?

**Comment by Sov-trotter** [comment]
There are two methods to work this out:

- Rather than using the `render` function we can simply pass `video` and `video.objects` to the `get_javis_frame` method along with the slider iterator(`using PlutoUI` inside the Pluto notebook).
- To not use the internal `get_javis_frame` method, we can create a `_pluto_viewer` method which basically stores all the frames as: 
    - `Array` of the image matrix(in-memeory) and then do something like 
 ```julia
   a = render(video, liveview = true)
    a[x] #x is the slider value
```
    - As frames in a temporary folder in the `pluto_notebooks` directory and the simply call those based on `x`

**Comment by Sov-trotter** [comment]
So in anyway, the user will have to declare the `Slider` method via  PlutoUI

**Comment by Sov-trotter** [comment]
https://user-images.githubusercontent.com/43717431/112682054-93732400-8e95-11eb-9a7b-70928153457f.mp4

When `liveviewer=false`

**Comment by TheCedarPrince** [comment]
WOW!!! @Sov-trotter - I could work with you on a PR to document how to use Pluto with Javis. I could go ahead and open one and ping you if you have time.

**Comment by Sov-trotter** [comment]
Would love that Thanks! I was able to solve the above issue with in-memory interactive viewer. Will push the changes in a while

**Comment by Wikunia** [comment]
Looks lovely! Thanks @Sov-trotter 
Will have a look at the PRs on Sunday. Will probably merge the Jupyter one if @TheCedarPrince is okay with that.

**Comment by TheCedarPrince** [comment]
I'll comment about Jupyter on that issue/PR - will jump over there @Wikunia
