### ISSUE TITLE
[BUG] liveview argument not documented

### ISSUE THREAD

**Issue by philtomson** [Wikunia/Javis.jl#209]
**Describe the bug**

No information about the _liveview_ argument to **javis** function. I had to search through closed bug reports about interactive drawing to find that it existed. I then did a search through the docs to see where it was documented and got no results. (also tried in the dev docs)

**Additional context**

This is a documentation request. Add info about _liveview = true_ to docs and tutorials.

**Comment by TheCedarPrince** [comment]
Hey @philtomson thank you very much for opening this issue!

Before you searched the documentation for the live viewer, did you try `?javis` inside your Julia REPL after you used it (i.e. `using Javis`)? When I do this, I can see an explanation about the kwarg related to `liveview` as follows:

![image](https://user-images.githubusercontent.com/29561456/94621496-68a96980-027e-11eb-99f7-bcff885843f5.png)

Also, I can also use `apropos("liveview")` where it returns the function where `liveview` is located:

![image](https://user-images.githubusercontent.com/29561456/94621971-47954880-027f-11eb-905d-bb59dc42c843.png)

You bring up an excellent point about easily finding materials. We are planning on adding a section to the documentation called "workflows" (#186) that includes explicit instructions about how to use the live viewer with development. Do you think that would be a sufficient solution for future users who may have the same problem as you? 

Sorry that you had such a hassle with using Javis! If you have any more problems/concerns/confusion, feel free to open additional issues, comment here, or create a discussion on our [Zulip stream here](https://julialang.zulipchat.com#narrow/stream/253420-javis).

Thank you for opening an issue - with help from users like you, we can make `Javis` even better! :smile:

**Comment by philtomson** [comment]
"Do you think that would be a sufficient solution for future users who may have the same problem as you?"

Mostly I think the liveview option should be mentioned in the tutorials so that it's easy to see it as an alternative to writing the animation out to a .gif file.

**Comment by TheCedarPrince** [comment]
Gotcha. Thanks for the feedback @philtomson . For now, I am going to leave this issue until #210 - if you think of anything else, let us know!

**Comment by Wikunia** [comment]
Thanks for opening the issue. Currently it's only part of our "how to" section https://wikunia.github.io/Javis.jl/stable/howto/#How-can-I-see-a-live-view-of-the-animation? But yeah maybe we can just add some description to our first tutorial.
