### ISSUE TITLE
Polar coordinates on Javis.jl (WARNING BRIGHT COLORS)

### ISSUE THREAD

**Issue by sudomaze** [Wikunia/Javis.jl#21]
## Background
I want to create a polar coordinates animation similar to this:
![](https://i.giphy.com/media/3o7aD56B2QS5MyTGfe/giphy.webp)
(Source: [Mesmerizing Looney Tunes GIF](http://gph.is/2xShiZ5) by Feliks Tomasz Konczakowski)

Currently, `Javis.jl` doesn't have this feature.

## Problem

Creating a polar coordinates animation

**Comment by Wikunia** [comment]
Thanks for the issue. If you want to work on a PR you probably want to check #18 
In general I prefer a less colorful version at the beginning by just creating circles outwards to create the polar coordinate system. Maybe also a spiral way of creating it. What do you think @sudomaze ?

**Comment by sudomaze** [comment]
I agree. The final form of the animation will be a polar coordinate like this one:

![](http://math.kennesaw.edu/~sellerme/sfehtml/classes/math2203/Fall2013/HTMLFiles/polarintegrals_12.gif)
(Source: [What does a polar coordinate system look like?](https://socratic.org/questions/what-does-a-polar-coordinate-system-look-like))

I don't think the circles should start from the center and expand is a good animation. I will try to have something like this (just the loading animation):

![](https://i.stack.imgur.com/7VozH.gif)
(Source: [Code animation - Convert a loading circle gif with check mark to animation based on JS](https://stackoverflow.com/questions/41329286/code-animation-convert-a-loading-circle-gif-with-check-mark-to-animation-based))
