### ISSUE TITLE
Better Warnings for SubAction Frame Ranges

### ISSUE THREAD

**Issue by TheCedarPrince** [Wikunia/Javis.jl#213]
**Is your feature request related to a problem? Please explain.**

It is hard to sometimes keep track of a SubAction being defined outside of the frames for a given Action. Further, it can lead to unintended consequences in future Actions if it is not clear where an issue is occurring.

**Describe the solution you'd like**

I would like to add the ability to add warnings such that if a SubAction is out of the range for the frames provided by an Action, then a warning is raised that unexpected behavior may occur.

**Comment by Wikunia** [comment]
Can you give an example for "Further, it can lead to unintended consequences in future Actions if it is not clear where an issue is occurring." ?
BTW why does this have the "question" label and why is this part of v0.3.0 and not v0.2.x? It seems very easy to fix and is not breaking.

**Comment by Wikunia** [comment]
I think we fixed this already in #278
