### ISSUE TITLE
Better Warnings for Objects without Background

### ISSUE THREAD

**Issue by TheCedarPrince** [Wikunia/Javis.jl#214]
**Is your feature request related to a problem? Please explain.**

It is hard to sometimes keep track of an Action being defined outside of the frames for a given animation. Especially in the case of defined BackgroundActions. Without a BackgroundAction, the Action will not render properly (if at all) and there ought to be  warning a user to this possible problem.

**Describe the solution you'd like**

I would like to add the ability to alert a user that a BackgroundAction frame is not present for a given Action that is defined outside the range provided by the BackgroundAction. A user could potentially define multiple different backgrounds so the solution will have to account for this.

**Comment by Wikunia** [comment]
Similar to #213 is this a question? Would also move this to v0.2.x

**Comment by Wikunia** [comment]
Seems like we fixed this already.
