### ISSUE TITLE
==> to a proper arrow in viewer

### ISSUE THREAD

**Issue by xiaodaigh** [Wikunia/Javis.jl#217]
The viewer has <== and ==> and I think it will look better with proper arrows.

**Comment by TheCedarPrince** [comment]
Could you make a PR on this @xiaodaigh? You would just need to change two strings in `src/javis_viewer.jl`. If you find some other symbols that may be better, let us know! 😃

**Comment by TheCedarPrince** [comment]
@Sov-trotter put in much work into trying to make this happen, but we ended up coming back to the same simple solution we started with. Feel free to look at his PR that was closed (#231) if you want to try to implement something. For now, however, I will close this issue.
