### ISSUE TITLE
Easier way of defining frames

### ISSUE THREAD

**Issue by Wikunia** [Wikunia/Javis.jl#22]
I have the feeling that defining frames for an Action is probably a tedious task for a full video or a more complex animation.
We should think about different ways like:
- `:all` for all frames
- `:same` same as the one before
- `Rel(10:20)` relative to the start of the one before so starting 10 frames after the one before and then going for 11 frames.

**Comment by TheCedarPrince** [comment]
Oh I really like this idea @Wikunia. Especially the `:same` symbol as that could potentially better ease the `FFMPEG` backend by making it not have to process as much.

As of right now, I am actually rather confused by how the frames work when called from an `Action` in the `javis` function. Would be happy to work on some documentation about it if you could explain it here a bit more.

**Comment by Wikunia** [comment]
I think we have a small miscommunication. I mean `:same` as the action before not as the frame before which should not happen that often or can have a special action called `Wait` or something which just uses the frame before. 

I am also thinking whether it's possible to create a video faster than creating images and use ffmpeg the way we do. 

Frames how they work now:
It's simple and stupid maybe 😄
i.e. 1:100 means this action is shown in frames 1 to 100. So for 30fps this means a bit more than 3 seconds.

We might want to define a way to use seconds as well to easily change the frame rate later. A lot can be done to make it easier for the user I think.

**Comment by Wikunia** [comment]
Let's have:
`:same` as the default
i.e
```
 Action(1:100, ground; in_global_layer=true),
 Action(1:90, :red_ball, (args...)->circ(p1, "red"), Rotation(from_rot, to_rot)),
 Action(Rel(10), :blue_ball, (args...)->circ(p2, "blue"), Rotation(2π, from_rot, :red_ball)),
 Action((video, args...)->path!(path_of_red, pos(:red_ball), "red")),
```
is the same as:
```
 Action(1:100, ground; in_global_layer=true),
 Action(1:90, :red_ball, (args...)->circ(p1, "red"), Rotation(from_rot, to_rot)),
 Action(91:100, :blue_ball, (args...)->circ(p2, "blue"), Rotation(2π, from_rot, :red_ball)),
 Action(91:100, (video, args...)->path!(path_of_red, pos(:red_ball), "red")),
```
