### ISSUE TITLE
fontsize and color in Javis instead of Luxor

### ISSUE THREAD

**Issue by Wikunia** [Wikunia/Javis.jl#23]
Currently the `latex` function needs a font size as well as I have no clue whether I can get the font size from Cairo/Luxor. Maybe @cormullion knows :smile: 

Same is treu for color where it might be helpful to for #15 to morph one shape with a color into another shape with a different color. For this we would need to get the color set in the two function to blend between the two colors.

**Comment by cormullion** [comment]
Good question. There are two text systems in Cairo: the Toy Api and the Other Api. Neither are that well supported - ie there are lots of Cairo functions that aren't yet implemented, and Cairo.jl has this odd pango business. I've given up trying to understand how it all works.

You will probably want to keep track of a font size and then specify it at the last moment...?

**Comment by Wikunia** [comment]
I would like to have functions `getfontsize` and `gethue` or something like that. Such that for our own functions we can access what was recently set. Several options: have that saved in the current drawing inside Luxor itself or build new functions to have it inside Javis or trying to look deeper into Cairo to get it from them.

**Comment by cormullion** [comment]
Ah, there's a get color  function already - I had the same problem trying to get the current color, so there's this https://github.com/JuliaGraphics/Luxor.jl/blob/9938a58161fc815d3937cb77767ed1eb3d6c3f89/src/basics.jl#L466 - not exported, though. 

I wish you'd been around in 2014/15... :)

**Comment by Wikunia** [comment]
Ah okay that's nice. Then I only need it for font size I guess. 

Back then I worked on Javascript stuff I guess. Not sure whether I was aware of Julia back then. Probably not.

**Comment by Wikunia** [comment]
Okay there is: https://www.cairographics.org/manual/cairo-text.html#cairo-get-font-matrix
which is currently not part of Cairo.jl

**Comment by Wikunia** [comment]
Btw you might be interested in #24 as well, as this is related to the colors being part of a layer.

**Comment by Wikunia** [comment]
I made a PR in Cairo to get the font matrix. If that works, I'll probably make a PR in Luxor to get the font size. https://github.com/JuliaGraphics/Cairo.jl/pull/331

**Comment by cormullion** [comment]
Great! I think there's lots of room for getting more powerful text features in - can you remember to document the "toy api"/"pro api" aspects of anything new, because it's very confusing when one tries to mix them. For example, `text_extents()` only works with the toy api, which cost me quite a few minutes of puzzlement once ... :)

**Comment by Wikunia** [comment]
I think I need to understand the difference between toy and pro first :smile: I never got much into text before. I'll try to figure it out the next days.

**Comment by Wikunia** [comment]
Can be used for`latex` once https://github.com/JuliaGraphics/Luxor.jl/pull/104 is merged and when Cairo and Luxor tag a new release :smile:
