### ISSUE TITLE
Better Way to Define Animation

### ISSUE THREAD

**Issue by TheCedarPrince** [Wikunia/Javis.jl#246]
**Is your feature request related to a problem? Please explain.**

Right now, defining an Animation to use for an animation is somewhat clunky as it inherits its format directly from the [`Animations.jl` package](https://github.com/jkrumbiegel/Animations.jl). This format I think is perfect for Animations.jl and those who have used it in the past but can be a bit difficult for a Javis user unfamiliar with Animations.jl.

Here is an example of the Javis syntax which invokes an `Animation` object:

```julia
anim = Animation([0.0, 1.0], [O, Point(1,100)], [linear()])
```

**Comment by TheCedarPrince** [comment]
Can we close this now @Wikunia ?

**Comment by Wikunia** [comment]
I currently don't know how to make it simpler so yeah why not.
