### ISSUE TITLE
Make Better Error Messages for v0.3.0

### ISSUE THREAD

**Issue by TheCedarPrince** [Wikunia/Javis.jl#249]
**Is your feature request related to a problem? Please explain.**

In Javis, it has often been unclear to know where an error occurs via the `Action` and `SubAction` syntax. This should not be! Therefore, let's do an exhaustive check of the new syntax we are making for Javis v0.3.0 to assist with better debugging. A check list of things to review could be:

- [x] Check `Object` syntax by defining bad functions or bad frame ranges or providing inappropriate `id` symbols.
- [x] Check `Action` syntax be providing bad frame ranges, modify the wrong `Object`, put it out of range of a previously defined `Object`, etc. #278 
- [x] Use invalid background functions for `Background`, attempt to modify `Background` with an `Action`, provide wrong unit ranges, provide unit ranges that do not cover all of the animation (#214), etc.
- [x] Put multiple video sources for render, have render show nothing even though `Object` items are defined, etc.

**Describe the solution you'd like**

Better warning messages for these items in case a user is having difficulty with producing a solution.

**Comment by TheCedarPrince** [comment]
Can we close this @Wikunia ?

**Comment by Wikunia** [comment]
I don't think we have done any of these tests. At least I haven't.

**Comment by Wikunia** [comment]
Unfortunately I find the points very vague i.e What do you mean by: invalid background functions? Like the function doesn't have `args...` as an input? 
What do you mean by "multiple video sources"

**Comment by TheCedarPrince** [comment]
I think we pretty thoroughly addressed this with #273 and #278 . Should be good now!
