### ISSUE TITLE
Tutorials for v0.1.0 Release

### ISSUE THREAD

**Issue by Wikunia** [Wikunia/Javis.jl#25]
Maybe this is good to be part of a tutorial on how to use Javis?

![trigo](https://user-images.githubusercontent.com/4931746/89107711-37a1e980-d433-11ea-9f57-7e64d3d49cb7.gif)

Thoughts @TheCedarPrince ?

**Comment by TheCedarPrince** [comment]
Oh that would be wonderful! I like this idea a lot! How do you think we should distribute tutorials? Like a Jupyter notebook or a markdown follow-along sort of tutorial where you follow directions?

Taking inspiration from [divio](https://documentation.divio.com/tutorials/)

**Comment by Wikunia** [comment]
I would do this similar to the one in Luxor.jl as we both found that one quite nice.

**Comment by TheCedarPrince** [comment]
Hey @sudomaze, any interest in taking this part on?

**Comment by TheCedarPrince** [comment]
Some thoughts for tutorials:

1. Making your first gif
2. How to make your own functions for Javis
3. Check out divio again for ideas [divio](https://documentation.divio.com/tutorials/)

**Comment by TheCedarPrince** [comment]
Add a tutorial about what actions are and how to use them (especially with subactions)

**Comment by TheCedarPrince** [comment]
Tutorials that will be worked on for v0.1.0 release of `Javis.jl`:

- [ ] An easy entry to making your first animation with `Javis.jl`
- [ ] What are Actions? How do they work? (include discussion about Subactions and Rel/:same)
- [ ] Javis can render LaTeX?!?!?
