### ISSUE TITLE
Latex alignment

### ISSUE THREAD

**Issue by Wikunia** [Wikunia/Javis.jl#277]
**Is your feature request related to a problem? Please explain.**
It's currently not possible to use `halign` and `valign` for `latex` whereas they are options for `text`. 

**Describe the solution you'd like**
In general `latex` should provide the same options as `text`.

**Comment by TheCedarPrince** [comment]
I think this issue could be tied to #224 - happy to take a look/work on it some.

**Comment by Wikunia** [comment]
Yeah might use similar functions

**Comment by codejaeger** [comment]
@Wikunia @TheCedarPrince can I try working on this issue?

**Comment by Wikunia** [comment]
Sure. Let us know if you need some help.
