### ISSUE TITLE
Have a set function similar to change which just sets the value

### ISSUE THREAD

**Issue by Wikunia** [Wikunia/Javis.jl#279]
**Is your feature request related to a problem? Please explain.**
Currently `change` can only be used when having values that define a `-` method and `*` to have interpolation.
Sometimes it might make sense to change other arguments like string though. Basically just setting the argument to a new value.

**Describe the solution you'd like**
I would like to have:

```julia
Action(1:1, set(:value, "new value"))
```
or something similar. 

**Describe alternatives you've considered**
It would only work with actions that have a single frame.
Therefore, we might want to allow `Action(1, set(:value, "new value"))` instead of forcing a unit range.

Another option would be have:

```julia
Action(1:1, change(:value, "new value"))
```

so we don't define a new function name but only have a single value instead of a pair. It will be set at the last frame defined such that it doesn't break for 

```julia
Action(1:2, change(:value, "new value"))
```

and just sets it for the frames `1:2` and then can be used with: `keep = false`

```julia
Action(1:2, change(:value, "new value"); keep=false)
```

to fall back to the default after frame 2.

**Comment by TheCedarPrince** [comment]
@Wikunia - I like this idea a lot! I see your point about having two separate functions. However, I agree a lot more with your latter idea: i.e. having change be a dispatch for the set functionality you were thinking of. I like the syntax of `Action(frame, change(:value, new_value); keep = Bool)`.

Perhaps we could implement something like this:

```julia
function _change(video, object, action, frame, s, vals, keep)
    if keep
        object.change_keywords[s] = vals[2]
    else
    ....
    end
end
```

and for the "normal" change:

```julia
function _change(video, object, action, rel_frame, s, vals, keep)
    if keep
        t = get_interpolation(action, rel_frame)
        val = vals[1] + t * (vals[2] - vals[1])
        object.change_keywords[s] = val
    else
    ....
    end
end
```

Where you could then use either a frame range or a specific frame to change a value and use the `keep` functionality to determine whether or not that value stays permanently mutated.

Happy to tackle this issue if you want!

**Comment by Wikunia** [comment]
I wouldn't add an extra keep for change. Isn't it the same as the keep for action?

**Comment by TheCedarPrince** [comment]
True! Got confused for a moment @Wikunia . I can look into implementing this - does that sound good?

**Comment by Wikunia** [comment]
Yeah you don't need to do anything with keep I think. That's implemented somewhere else. Give it a go and I review

**Comment by Wikunia** [comment]
Sorry I needed it yesterday so I've implemented it.
