### ISSUE TITLE
Morphing should change the object

### ISSUE THREAD

**Issue by Wikunia** [Wikunia/Javis.jl#286]
**Is your feature request related to a problem? Please explain.**
Currently it's a bit hard to morph an object and then change the color of the morphed object afterwards. This is due to the fact that morphing doesn't really change the object. 

**Describe the solution you'd like**
I think we should consider actually changing the object function by the `morph_to` function. The problem here is that it would make it impossible to work with `liveview`. Therefore, we might want to have it inside the `ObjectSetting` instead such that we could overwrite the function without loosing the user defined function.

**Describe alternatives you've considered**
Another possibility would be that we can somehow return an object from `act!` but that feels weird as well.

**Comment by Sov-trotter** [comment]
https://azarzadavila-manim.readthedocs.io/en/latest/animation.html#transform

**Comment by Sov-trotter** [comment]
![testmorph](https://user-images.githubusercontent.com/43717431/126033804-57e54762-959c-4c72-abb8-03c1cb9787a8.gif)

**Comment by Sov-trotter** [comment]
So the way this currently works is, by replacing the object's function. 
So something like:
```julia
# inside the morph_to function
if frame == last(get_frames(action))
        object.func = to_func
    else
        # the morphing computation
        newpath()
        ....
        return morph_between(video, action, frame, from_polys, to_polys; do_action = do_action)
    end
```
