### ISSUE TITLE
Update contributing.md

### ISSUE THREAD

**Issue by TheCedarPrince** [Wikunia/Javis.jl#29]
## Problem

Due to some miscommunication between Slack, GitHub, and code commits, I am going to solidify the documentation about how to document functions in this codebase.

## Solution

Going to add best practices we follow to `contributing.md` and possibly going to make some additional documentation files if the need arises.

@Wikunia aside from specifying that we will completely document exported functions and minimally document internal functions, is there anything else you can think of to add or clarify?

**Comment by Wikunia** [comment]
Just a small note: Not only functions but also `types`.
You might want to mention the way to link between functions there as well.

**Comment by TheCedarPrince** [comment]
When you say `types` what do you mean by that? Could you give me an example of what you are thinking?

What do you mean by "the way to link between functions"? Confused by what you are saying there.

**Comment by Wikunia** [comment]
`type` = (mutable) `struct` :wink: 
Maybe give an example of 
```
[`javis`](@ref)
```

**Comment by TheCedarPrince** [comment]
This is going to be one of the final issues I am going to check before we release because I want to run my formatter on everything and do a thorough comparison to BlueStyle to make sure we are in good shape. :+1:
