### ISSUE TITLE
[BUG] Cannot install Javis

### ISSUE THREAD

**Issue by bharatbhole** [Wikunia/Javis.jl#293]
**Before Filing a Report**

- Did I read the Documentation and/or docstrings?
   Yes, I did. I could not find the minimum required Julia version.

- Did I search the Javis GitHub to see if this bug has already been reported?
   Yes, I did. But the solution there did not help.

**Describe the bug**

I am using Julia version 1.0.5, the Long term support release. When I tried installing Javis I got the following output:

```
v1.0) pkg> add Javis
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Javis [78b212ba]:
 Javis [78b212ba] log:
 ├─possible versions are: [0.1.0-0.1.5, 0.2.0-0.2.2, 0.3.0-0.3.1] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.1.0-0.1.5, 0.2.0-0.2.2, 0.3.0-0.3.1]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

**To Reproduce**

1. Julia Version (i.e. output of `julia -v`):

`julia version 1.0.5`

2. Operating system (Mac, Linux, Windows):

`Mac 10.14.6`

3. Javis version (i.e output of `] status Javis` in the REPL)

Not applicable.

Thank you. I hope to use Javis. It looks interesting. I hope it works with LTS release of Julia.

**Comment by TheCedarPrince** [comment]
Hey @bharatbhole - thanks for opening the issue!

Currently, Javis only works for Julia version 1.4+. I grabbed Julia 1.0.5 to test out lowering compats and the more I did this, the more compatibility conflicts we had with existing dependencies. I am going to say unfortunately, we may not be able to support lower versions.

What do you think @Wikunia ?

**Comment by Wikunia** [comment]
Thanks for the interest in Javis! @bharatbhole 
Unfortunately as mentioned by @TheCedarPrince we choose to not support the LTS as there were some conflicts and the package is quite new. 

Therefore we decided as the next LTS shouldn't be too far away (maybe 6 months) to not support it for now and instead support the next LTS.

Is there a specific reason to use the LTS for you? 
You might want to install a newer version for some projects. It's quite common to have several Julia versions installed at the same time.

**Comment by bharatbhole** [comment]
Thank you for your responses @Wikunia and @TheCedarPrince .

The reason I am using the LTS release is that I often have problems with many third party packages when I using the latest stable release. I have never had a problem with LTS release before. 

I think, as you suggested, working with multiple Julia versions may be the solution. I will try that out.

Thank you.

**Comment by Wikunia** [comment]
It's a bit unfortunate but I think newer packages are currently going in the same direction to support the future LTS as we want to use all the new cool features :smile: 
Hope the suggested way works well for you.

Enjoy Javis :wink:
