### ISSUE TITLE
Use `Point(0, 0)` rather than `O` in early stages of the tutorial/documentation?

### ISSUE THREAD

**Issue by cormullion** [Wikunia/Javis.jl#296]
The shortcut `O` for `Point(0, 0)` is very convenient, but it sometimes causes problems when people are trying out examples and tutorials. Even if the typography is trying to help them, they'll often assume that an O on its own is a 0. I've seen a few people¹ report issues when trying examples in both Luxor and Javis where they've automatically typed a single 0 instead of the O that was expected.

I'd suggest that, in the early stages of our tutorials and documentation, we use `Point(0, 0)`, as a useful reminder to supply a pair of coordinates. Perhaps introduce the `O` shortcut halfway through a tutorial? 

1: A recent example: https://discourse.julialang.org/t/question-about-javis-jl/50811/7

**Comment by agerlach** [comment]
I agree completely. When I first looked at the Javis tutorials I was extremely confused by all the `O` everywhere. I couldn't understand the code by just looking at it.

**Comment by Wikunia** [comment]
Thanks for the feedback @cormullion and @agerlach.
Will add it as soon as I have time.
