### ISSUE TITLE
Non animated Transition 

### ISSUE THREAD

**Issue by Wikunia** [Wikunia/Javis.jl#33]
Sometimes it might be reasonable to write `Translation(Point(x,y))` which does not depend on the frame instead of writing
`Translation(Point(x,y), Point(x,y))` so I think it makes sense to have a constructor which takes in one value and just uses that one value as the starting and the end of the animation such that there is no animation. Hope that makes sense :smile: 

See #32 as an example.

**Comment by TheCedarPrince** [comment]
This makes sense and I definitely see the utility in this. I was actually thinking about something similar to this earlier today. My thought was along the lines about how if a user wants to draw a circle at the beginning of the animation, then the circle drawing would persist throughout the rest of the animation.

Spawning from that thought was this additional one: Do you think there may be occasion to also make a kwarg for `BackgroundAction` such that if a user only wants actions to run at the beginning of the animation (e.g. drawing shapes or designs on the background of the animation), it will only be run then and not interfere with any of the other Actions? Of course, the animation would need to be redrawn on future frames.

I may be explaining this poorly but what I see beginning to emerge as I am starting to experiment with Javis is that it may be convenient to create clearer distinction between Actions and Background Actions. I am just not sure what would be the best way to continue with clarifying this distinction. Unless you think that Background Actions is sufficient.

**Comment by Wikunia** [comment]
I think I don't really understand what you're referring to and I closed this issue as it's implement, You might want to create a new issue for your thoughts :wink: 

It feels a bit like you're confusing `BackgroundAction` with actions that only show at the beginning? I'm confused :smile: 
The Actions itself always in which frames they are called.

**Comment by Wikunia** [comment]
Okay I want to reopen this for a different reason. It might make sense to see 
`Translation(Point(50, 50))` not as a constant translation but as a translation from the origin to `(50, 50)` 
Actually I think this would be used more often. :confused:

**Comment by TheCedarPrince** [comment]
@Wikunia you are correct. I re-examined my thoughts and I was confusing myself with `Actions`. I might open an issue in the future, but for now, I think we're fine.

Regarding reopening the issue, I see what you're saying. I could see getting confused by that personally. Maybe what might be useful is to make some sort of special kwarg like `anchor` that can be loosely defined as when you want an animation to not be moved from its current position. In code, this could still be seen as `Translation(Point(50, 50))` for `anchor=true` or something along those lines. 

Or perhaps a different kwarg that looks something like this `translation::String = nothing` which would cause the animation to stay where it is and `translation::Tuple` which accepts a tuple object that represents (start, end) positions. The latter `translation` would then pass that tuple to a `Translation` to execute the proper execution.

What do you think?

**Comment by Wikunia** [comment]
Thanks for you thoughts. I kinda like the idea of having a struct for it and not a `kwarg` as with your approach it would not be possible to translate and rotate an object or it would be not possible to distinguish it from rotate and then translate. In the current approach one can do first translate then rotate then translate and another rotation. Which one might be able to compress to less commands but maybe it's easier to write it down in this way. 

Hope that makes sense.

**Comment by Wikunia** [comment]
Translations are always from origin such that
`Translation(10,10) = Translation(Point(10,10))`
is what currently `Translation(O, Point(10,10))` does.

One can provide a start point and an end point, but it's possible to define only the end point (default start is origin)

Sames goes for `Rotation` where it would start at `0` angle.

This reverts: #35
