### ISSUE TITLE
Extension to RFrames

### ISSUE THREAD

**Issue by codejaeger** [Wikunia/Javis.jl#331]
**Is your feature request related to a problem? Please explain.**
When specifying a relative frame range it would be would be nice to have an option to specify if the reference frame was the previous object's first or last frame. A particular use case is when objects need to be added to the canvas one after another based on their starting frame.

**Describe the solution you'd like**
Add the argument `from_start::Bool` to `RFrames` to indicate the frame range for this object. 
Example:
```
ball = Object(Rframes(5:10, true), (args...)->somefunc())
```

**Describe alternatives you've considered**
A workaround is to create a function to access the starting frame of the desired object in a way like `start(obj)`. The only problem seems to be when the previous object (or a reference to it) is not known.

**Additional context**
Both the methods were suggested by @Wikunia on Javis' zulip [thread](https://julialang.zulipchat.com/#narrow/stream/253420-javis/topic/Extension.20to.20Rframes.3F).

**Comment by Wikunia** [comment]
Thanks for opening the issue. Yeah the function might need some extra work. Interested in ideas by @Sov-trotter

**Comment by Sov-trotter** [comment]
Thanks for the ping @Wikunia . I'll get back here in a few days as I am currently out of town. 😀

**Comment by TheCedarPrince** [comment]
I think we can close this issue based on the above Zulip discussion. :D
