### ISSUE TITLE
Explanation of origin O in Tutorial 1 still not clear

### ISSUE THREAD

**Issue by adediego** [Wikunia/Javis.jl#332]
Hey there, nice package! 

Just wanted to mention that I still got confused by the shortcut ```O``` in the Tutorial 1. I saw that you added an explanation recently in #301 but it did not really help me in that moment as I read ```O``` as ```0``` without even thinking. 
I had to look at a diff between copypasted code and the code I typed to find out, what was wrong. 

I think it is better to write "the letter ```O```" and not "the character ```O```". That's also how Luxor.jl does it in their Tutorial.

**Comment by Wikunia** [comment]
Hi @adediego , do you mind opening a PR with that? :wink: 
It's definitely welcome :smile:
