### ISSUE TITLE
Enable Layers to Have Clear Backgrounds

### ISSUE THREAD

**Issue by TheCedarPrince** [Wikunia/Javis.jl#344]
**Is your feature request related to a problem? Please explain.**

Layers are cool - let's make them even cooler by adding in transparency. :dark_sunglasses: 

**Describe the solution you'd like**

Ideally, I would like layers to have the ability to have fully transparent backgrounds. The objects on this layer wouldn't be transparent but rather, everything but the objects would be.

**Describe alternatives you've considered**

One could make the backgrounds for each layer match the global layer but that isn't actual transparency but rather camoflauge.

**Additional context**

Perhaps the logic could work like:

1. Set `opacity = :transparent`
2. Determine where on each layer matrices are default values
3. Compare them with the global layer
4. If a coordinate is defined in the global layer, set the value in the layer to that value
5. If not, keep the default empty value.
6. Otherwise, if layer defines a value at a coordinate, put the value in that layer there as precedent. 

Little vague so will have to think of it some more!

**Comment by Sov-trotter** [comment]
I am not sure if I understand this correctly but if we don't define a `Background` in the layer, it does end up being transparent. In fact the entire drawing that holds all the layers is itself transparent

**Comment by TheCedarPrince** [comment]
Hey @Sov-trotter - just ignore this issue for now. Just was putting it here before I forgot. :)

**Comment by Wikunia** [comment]
Can we close this @TheCedarPrince as it's possible in to set `:opaque` or `:transparent` in #343 now

**Comment by TheCedarPrince** [comment]
Sure! I have been watching that discussion on #342 with excitement as I see we are getting this functionality. :)
