### ISSUE TITLE
Mismatch in the default position of origin as per javis docs vs Luzor docs.

### ISSUE THREAD

**Issue by Ved-Mahajan** [Wikunia/Javis.jl#351]
It seems like there is a mismatch in the default position of origin as given in the Luxor documentation vs what Javis documentation.

As per Javis documentation: `Luxor has its default origin in the center of the canvas and the y-axis is pointing down.`

![Screenshot from 2021-06-22 23-16-29](https://user-images.githubusercontent.com/74182892/123139126-7d183c80-d473-11eb-9d91-f83ed6d2c068.png)

And as per Luxor documentation: `The default origin is at the top left of the drawing area, but you can reposition it at any time`

![Screenshot from 2021-06-22 23-16-52](https://user-images.githubusercontent.com/74182892/123139133-7ee20000-d473-11eb-943c-9c91a333f70b.png)

**Comment by Wikunia** [comment]
Hey there,
Luxor has actually kind of several defaults. 
Often one uses the `@png` macro such as:
```julia
@png begin
    text("Hello world")
    circle(Point(0, 0), 200, :stroke)
end
```
which is copied from their tutorial. In those macros the origin is set to the center of the image which is then the default we use for Javis. Hope that clarifies the "mismatch".

**Comment by TheCedarPrince** [comment]
Did that help @Ved-Mahajan ? Can we close this issue?

**Comment by Ved-Mahajan** [comment]
Yeah yeah absolutely.

Sorry this issue slipped out of my mind .
