### ISSUE TITLE
Revolution bug in cosmic dance example

### ISSUE THREAD

**Issue by Sov-trotter** [Wikunia/Javis.jl#358]
The example in https://github.com/Wikunia/Javis.jl/pull/352 here -> https://github.com/Wikunia/Javis.jl/blob/master/examples/cosmic_dance.jl#L45-L51 is a bit incorrect.

If you see the gif https://github.com/Wikunia/Javis.jl/blob/master/examples/gifs/cosmic_dance.gif?raw=true earth completes 1 revolution around the sun(365 days) before venus (224.7) which seems a bit odd.
I think the actions should be something like 
```julia
    act!(earth, Action(anim_rotate_around(12.5 * 2π* (224.7 / 365), O)))
    act!(venus, Action(anim_rotate_around(12.5 * 2π , O)))

```
This doesn't affect the pattern formed in any way though.
Pinging @Ved-Mahajan .

**Comment by Ved-Mahajan** [comment]
@Sov-trotter you are indeed correct.
It was a mistake on my part. Thanks a lot for pointing it out!

Is this something that you can fix or should I make a PR?

**Comment by Sov-trotter** [comment]
Since this is relatively simple. I think it'd be better to tag this issue as a good first issue. Or if you can make a pr, that'd be good?

**Comment by TheCedarPrince** [comment]
@Ved-Mahajan - it would be great if you could make a PR! Happy to review. 😄
