### ISSUE TITLE
Animate change of color

### ISSUE THREAD

**Issue by Sov-trotter** [Wikunia/Javis.jl#363]
I couldn't really figure out a way to fill color in a shape gradually(not instantly).
eg: Something like 
```julia
act!(star_obj, Action(41:50, change(:do_action, :fill)))
act!(star_obj, Action(41:50, change(:color, "red")))
``` 
Fills color in the 41st frame rather than animating the filing.

**Comment by Wikunia** [comment]
`change` takes either something of the form `a => b` or a value. When given a value like here it just sets the value without animation.

**Comment by Sov-trotter** [comment]
OH!
Something like `change(:color, "white"=>"red")` throws an error. 
```
ERROR: LoadError: MethodError: no method matching -(::String, ::String)
Closest candidates are:
  -(::ChainRulesCore.NotImplemented, ::Any) at /home/ezio/.julia/packages/ChainRulesCore/4bCB1/src/differential_arithmetic.jl:62
  -(::ChainRulesCore.NoTangent, ::Any) at /home/ezio/.julia/packages/ChainRulesCore/4bCB1/src/differential_arithmetic.jl:77
  -(::ChainRulesCore.ZeroTangent, ::Any) at /home/ezio/.julia/packages/ChainRulesCore/4bCB1/src/differential_arithmetic.jl:117
  ...
Stacktrace:
  [1] _change(video::Video, object::Object, action::Action, rel_frame::Int64, s::Symbol, vals::Pair{String, String})
    @ Javis ~/.julia/dev/Javis/src/action_animations.jl:419

```

**Comment by Wikunia** [comment]
Yeah because it can't interpolate. I think you can use `RGB` from the colors package though

**Comment by Sov-trotter** [comment]
Oh yeah. Better to tag it as a `goodfirstissue` or we might take a look at it later.

**Comment by Wikunia** [comment]
Just for clarification: you meant interpolation of the fill color and not filling a circle from top to bottom for example, right? That might be interesting as well though. 
Regarding the change function a bit more: the problem we faced is that we don't know the initial color and therefore need this pair for interpolation. With #313 there might be a way to fix this as well, right?

**Comment by Sov-trotter** [comment]
Yeah. Filling from top to bottom can go in the `draw` action. 
I think the user has to provide the previous color then. Just like we do it for radius and other properties.

**Comment by TheCedarPrince** [comment]
We could chat more @Sov-trotter , but here is how I would do it right now without convenience functionalities:

```julia
using Javis, Animations, Colors

function ground(args...)
    background("black")
    sethue("white")
end

color_anim = Animation(
    [0, 0.25, 0.5, 0.75, 1], # must go from 0 to 1
    [Lab(colorant"black"), Lab(colorant"red"), Lab(colorant"cyan"), Lab(colorant"red"), Lab(colorant"black")],
    [sineio(), sineio(), sineio(), sineio()],
)

video = Video(600, 400)
Background(1:200, ground)

    blob = Object(1:150, (args...) -> circle(O, 60, :fill))
    act!(blob, Action(1:150, color_anim, sethue()))

render(
    video;
    pathname = "loading.gif",
)
```

Which gives: 

![loading](https://user-images.githubusercontent.com/29561456/126055175-82cf2c95-92c4-4565-b2fd-c8b6c06b1164.gif)

Obviously a bit verbose. Would be nice to make some reasonable default animation syntax for change where we could have something like:

```
act!(star_obj, Action(41:50, change(:do_action, :fill)))
act!(star_obj, Action(41:50, change(:color, colorant"red" => colorant"blue", sineio())))
```
