### ISSUE TITLE
[BUG] Error in executing functions in tutorial

### ISSUE THREAD

**Issue by paniash** [Wikunia/Javis.jl#365]
**Before Filing a Report**

- Did I read the Documentation and/or docstrings? Yes
- Did I search the Javis GitHub to see if this bug has already been reported? Yes
- Am I familiar with the Javis philosophy? No
- Do I have the latest version of Javis installed? Yes

**Describe the bug**

Following [this](https://wikunia.github.io/Javis.jl/stable/tutorials/tutorial_1/) tutorial, when trying to run the following snippet of code:

```julia
Background(1:70, ground)
red_ball = Object(1:70, (args...)->object(O, "red"), Point(100,0))
act!(red_ball, Action(anim_rotate_around(2π, O)))
blue_ball = Object(1:70, (args...)->object(O, "blue"), Point(200,80))
act!(blue_ball, Action(anim_rotate_around(2π, 0.0, red_ball)))
Object(1:70, (args...)->connector(pos(red_ball), pos(blue_ball), "black"))
Object(1:70, (args...)->path!(path_of_red, pos(red_ball), "red"))
Object(1:70, (args...)->path!(path_of_blue, pos(blue_ball), "blue"))

render(myvideo; pathname="tutorial_1.gif")
```

I receive errors that suggest that functions like `Background` or `anim_rotate_around()` are not defined.

**To Reproduce**

1. Julia Version (i.e. output of `julia -v`): 1.6.2

2. Operating system (Mac, Linux, Windows): Linux

3. Javis version (i.e output of `] status Javis` in the REPL) v0.1.5

4. Minimum working code example that led to bug:

```julia
using Javis

function ground(args...)
    background("white") # canvas background
    sethue("black") # pen color
end

function object(p=O, color="black")
    sethue(color)
    circle(p, 25, :fill)
    return p
end

function path!(points, pos, color)
    sethue(color)
    push!(points, pos) # add pos to points
    circle.(points, 2, :fill) # draws a circle for each point using broadcasting
end

function connector(p1, p2, color)
    sethue(color)
    line(p1,p2, :stroke)
end

myvideo = Video(500, 500)

path_of_red = Point[]
path_of_blue = Point[]

Background(1:70, ground)
red_ball = Object(1:70, (args...)->object(O, "red"), Point(100,0))
act!(red_ball, Action(anim_rotate_around(2π, O)))
blue_ball = Object(1:70, (args...)->object(O, "blue"), Point(200,80))
act!(blue_ball, Action(anim_rotate_around(2π, 0.0, red_ball)))
Object(1:70, (args...)->connector(pos(red_ball), pos(blue_ball), "black"))
Object(1:70, (args...)->path!(path_of_red, pos(red_ball), "red"))
Object(1:70, (args...)->path!(path_of_blue, pos(blue_ball), "blue"))

render(myvideo; pathname="tutorial_1.gif")
```

**Expected Behavior and Actual Behavior**

Expected: Generation of the final gif file.
Actual: End up with errors suggesting that certain functions are undefined.

**Stacktrace (If Applicable)**

```
ERROR: LoadError: UndefVarError: Background not defined
Stacktrace:
 [1] top-level scope
   @ ~/misc/git-repos/progs/code/julia/javis.jl:30
in expression starting at /home/ashish/misc/git-repos/progs/code/julia/javis.jl:30
```

**Comment by Wikunia** [comment]
Hi @paniash,
Javis is currently at version 0.5.2 which means your local version is quite old 😅
You probably have too many other things inside your global environment which are incompatible?
Try creating a local environment in which you install Javis and other packages you need for your animation.
You can read more about that on my blog: https://opensourc.es/blog/all-about-pkg/

Let me know if that doesn't solve the issue. 
Have fun with Javis 😊

**Comment by paniash** [comment]
@Wikunia Ah, my bad. Thanks for letting me know. I tried your suggestion after reading your (wonderful!) blog and it works well!

Thanks!
