### ISSUE TITLE
[BUG] anim_translate feels broken. How to fix?

### ISSUE THREAD

**Issue by Wikunia** [Wikunia/Javis.jl#367]
**Describe the bug**

As an example by @simeonschaub I had a look at `anim_translate` again and have the feeling that it's kinda broken but I don't have a simple fix in mind. 

The code:
```julia
using Javis
function ground(args...)
    background("white") # canvas background
    sethue("black") # pen color
end
function object(p=O, color="black")
    sethue(color)
    circle(p, 25, :fill)
    return p
end
myvideo = Video(500, 500)
Background(1:70, ground)
upper_ball = Object(1:70, (args...)->object(O, "red"), Point(0, -100*√3))
left_ball = Object(1:70, (args...)->object(O, "green"), Point(-100, 0))
right_ball = Object(1:70, (args...)->object(O, "blue"), Point(100, 0))
act!(left_ball,  Action(anim_translate(Point(2 * 100, 0))))
act!(right_ball, Action(anim_translate(Point(2 * -100, 0))))
render(myvideo; pathname="triangle.gif")
```

It currently produces:

![javis_VNNDI7e](https://user-images.githubusercontent.com/4931746/126311679-5570e230-c1f2-4095-b02b-3c7658bd97f2.gif)

but expected would have been:

![triangle](https://user-images.githubusercontent.com/4931746/126311576-482910a6-15cc-46e6-9261-ee33b2ddd246.gif)

especially based on our docstring:
```julia
- `anim_translate(x::Real, y::Real)` define end point of translation
- `anim_translate(tp::Union{Object,Point})` define end point with [`Object`](@ref) or `Point`
```

Now the first question is: Do we want to define the end point or not?
- It seems cool to have this possibility and @simeonschaub clearly expected that behavior (not sure whether this was based on the docstring or intuition)

The problem here is the following:

```julia
left_ball = Object(1:70, (args...)->object(O, "green"), Point(-100, 0))

act!(left_ball,  Action(1:70, anim_translate(Point( 100, 0))))
act!(left_ball,  Action(1:70, anim_translate(Point( 0, 100))))

render(myvideo; pathname="counter_example.gif")
```

The intuition from before seems to break down when two `anim_translate` functions are acted on at the same time.
What should this do? If we have the end point idea from before it should somehow be at two places at the same time...
Should this just be avoided? Or it it better to see `anim_translate` as forces and the end point is `Point(0, 100)` ?
In that case the user has to keep track of the current position. 

Another option is to have a function `anim_translate_to` which uses the position at the start of the action as a reference point and updates the position at the end of the action. 

Looking forward to your inputs @TheCedarPrince @Sov-trotter @cormullion

**Comment by simeonschaub** [comment]
> It seems cool to have this possibility and @simeonschaub clearly expected that behavior (not sure whether this was based on the docstring or intuition)

I did read the docstring, so I expected the end point to be in absolute coordinates. If this is nontrivial to fix, it would be good to properly document the current behavior at least.

Not sure if this is related, but I did actually also try to pass an `Object` (i.e. `right_ball`/`left_ball`) to `anim_translate`, which errored. According to the docstring, that should work, right?

**Comment by Wikunia** [comment]
Yeah currently it is definitely broken in the regard that the docstring doesn't represent what's actually happening. 
Having `right_ball` in the `anim_translate` should work (means: shouldn't error) but should also not really do what you expect I suppose as the position gets constantly updated so it does not mean the start position of the `right_ball` but the current position of it. Which I think should result in they are getting closer to each other and meet in the middle.

**Comment by Wikunia** [comment]
Some more thoughts on it:
- I think providing the target makes sense and then throwing an error if there are two actions use this functionality in the same time frame. Maybe rename the function to `anim_translate_to`
- Then having an additional function `anim_translate_by` 

Regarding your problem with having the object itself inside the function @simeonschaub : 
- You reference the position of the one object before that is known. So you can have:
```julia
left_ball = Object(1:70, (args...)->object(O, "green"), Point(-100, 0))
right_ball = Object(1:70, (args...)->object(O, "blue"), Point(100, 0))

# act!(left_ball,  Action(1:70, anim_translate(right_ball)))
act!(right_ball,  Action(1:70, anim_translate(left_ball)))
```
but when you comment out the other `act!` line you reference the position of `right_ball` before that is really known as the `right_ball` function is not drawn yet at that stage such that `return p` in the `object` function isn't called and therefore unknown.

**Comment by TheCedarPrince** [comment]
For reference, before it is lost to the Julia Slack hole, this is the code snippet for the animation that produces the desired output:

<details>

<summary>Creates a gif where the green and blue balls swap positions</summary>

```julia
using Javis
function ground(args...)
    background("white") # canvas background
    sethue("black") # pen color
end
function object(p=O, color="black")
    sethue(color)
    circle(p, 25, :fill)
    return p
end
myvideo = Video(500, 500)
Background(1:70, ground)
upper_ball = Object(1:70, (args...)->object(O, "red"), Point(0, -100*√3))
left_ball = Object(1:70, (args...)->object(O, "green"), Point(-100, 0))
right_ball = Object(1:70, (args...)->object(O, "blue"), Point(100, 0))
act!(left_ball,  Action(anim_translate(Point(2 * 100, 0))))
act!(right_ball, Action(anim_translate(Point(2 * -100, 0))))
render(myvideo; pathname="triangle.gif")
```
</details>

From the code example, one currently had to multiply the position by a factor of two to get the desired outcome. Per @Wikunia and @simeonschaub 's point, I see where Simeon is coming from with regards to how it should work based off our current docstring - which is broken. Sorry for the mis-attribution of this issue to Luxor.jl @cormullion ! Also following up on discussion with Ole on a call, I think there is a fundamental confusion with the `anim` family of functions and we will probably need to revisit `anim` functions more thoroughly in a separate issue.

As a stopgap, I think a good fix would be to update the docstring here to make it clear what `anim_translate` actually do.
