### ISSUE TITLE
[BUG] latex: tex2svg might not be installed

### ISSUE THREAD

**Issue by arunningcroc** [Wikunia/Javis.jl#384]
**Describe the bug**

Unable to use LaTeX, because Julia can't find tex2svg when running it with "open". This is despite of the fact that I installed the required node module with 

`npm install -g mathjax-node-cli`

and ensured that the relevant location (AppData\Roaming\npm) is in PATH. tex2svg works fine from cmd and Powershell from any directory.

**To Reproduce**

1. Julia Version (i.e. output of `julia -v`): 1.6.2

2. Operating system (Mac, Linux, Windows): Windows 10

3. Javis version (i.e output of `] status Javis` in the REPL): 0.6.0

4. Minimum working code example that led to bug: v 0.6.0

**Expected Behavior and Actual Behavior**

Should render latex correctly and find the tex2svg program, as it is in PATH. Instead fails with a long stack trace.

**Stacktrace (If Applicable)**
```
`┌ Warning: Using LaTeX needs the program `tex2svg` which might not be installed
└ @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\latex.jl:151
[ Info: It can be installed using `npm install -g mathjax-node-cli`
ERROR: LoadError: IOError: could not spawn `tex2svg '\begin{equation}
\left[\begin{array}{cc}
2 & 3 \\  4 & \sqrt{5} \\
\end{array} \right]
\end{equation}'`: no such file or directory (ENOENT)
Stacktrace:
  [1] get_latex_svg(text::LaTeXString)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\latex.jl:153
  [2] animate_latex(text::LaTeXString, pos::Point, t::Float64, valign::Symbol, halign::Symbol, object::Symbol)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\latex.jl:85
  [3] latex(text::LaTeXString, pos::Point, draw_object::Symbol; valign::Symbol, halign::Symbol)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\latex.jl:81
  [4] latex
    @ C:\Users\USER\.julia\packages\Javis\FLdWO\src\latex.jl:6 [inlined]
  [5] draw_latex(video::Video, action::Object, frame::Int64)
    @ Main C:\Users\USER\Documents\Fysiikka\latex.jl:13
  [6] draw_object(object::Object, video::Video, frame::Int64, origin_matrix::Matrix{Float64}, layer_frames::Nothing)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:607
  [7] macro expansion
    @ C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:363 [inlined]
  [8] macro expansion
    @ C:\Users\USER\.julia\packages\Luxor\XHa4Y\src\basics.jl:520 [inlined]
  [9] render_objects(objects::Vector{Javis.AbstractObject}, video::Video, frame::Int64; layer_frames::Nothing)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:362
 [10] render_objects
    @ C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:335 [inlined]
 [11] get_javis_frame(video::Video, objects::Vector{Javis.AbstractObject}, frame::Int64; layers::Vector{Javis.AbstractObject})
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:550
 [12] macro expansion
    @ C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:278 [inlined]
 [13] macro expansion
    @ C:\Users\USER\.julia\packages\ProgressMeter\Vf8un\src\ProgressMeter.jl:940 [inlined]
 [14] render(video::Video; framerate::Int64, pathname::String, liveview::Bool, streamconfig::Nothing, tempdirectory::String, ffmpeg_loglevel::String)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:277
 [15] top-level scope
    @ C:\Users\USER\Documents\Fysiikka\latex.jl:28
in expression starting at C:\Users\USER\Documents\Fysiikka\latex.jl:28
```

caused by: 
```
IOError: could not spawn `tex2svg '\begin{equation}
\left[\begin{array}{cc}
2 & 3 \\  4 & \sqrt{5} \\
\end{array} \right]
\end{equation}'`: no such file or directory (ENOENT)
Stacktrace:
  [1] _spawn_primitive(file::String, cmd::Cmd, stdio::Vector{Any})
    @ Base .\process.jl:99
  [2] #637
    @ .\process.jl:112 [inlined]
  [3] setup_stdios(f::Base.var"#637#638"{Cmd}, stdios::Vector{Any})
    @ Base .\process.jl:196
  [4] _spawn
    @ .\process.jl:111 [inlined]
  [5] open(cmds::Cmd, stdio::Base.DevNull; write::Bool, read::Bool)
    @ Base .\process.jl:370
  [6] open
    @ .\process.jl:361 [inlined]
  [7] open(cmds::Cmd, mode::String, stdio::Base.DevNull)
    @ Base .\process.jl:341
  [8] read(cmd::Cmd)
    @ Base .\process.jl:410
  [9] read(cmd::Cmd, #unused#::Type{String})
    @ Base .\process.jl:421
 [10] get_latex_svg(text::LaTeXString)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\latex.jl:149
 [11] animate_latex(text::LaTeXString, pos::Point, t::Float64, valign::Symbol, halign::Symbol, object::Symbol)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\latex.jl:85
 [12] latex(text::LaTeXString, pos::Point, draw_object::Symbol; valign::Symbol, halign::Symbol)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\latex.jl:81
 [13] latex
    @ C:\Users\USER\.julia\packages\Javis\FLdWO\src\latex.jl:6 [inlined]
 [14] draw_latex(video::Video, action::Object, frame::Int64)
    @ Main C:\Users\USER\Documents\Fysiikka\latex.jl:13
 [15] draw_object(object::Object, video::Video, frame::Int64, origin_matrix::Matrix{Float64}, layer_frames::Nothing)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:607
 [16] macro expansion
    @ C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:363 [inlined]
 [17] macro expansion
    @ C:\Users\USER\.julia\packages\Luxor\XHa4Y\src\basics.jl:520 [inlined]
 [18] render_objects(objects::Vector{Javis.AbstractObject}, video::Video, frame::Int64; layer_frames::Nothing)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:362
 [19] render_objects
    @ C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:335 [inlined]
 [20] get_javis_frame(video::Video, objects::Vector{Javis.AbstractObject}, frame::Int64; layers::Vector{Javis.AbstractObject})
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:550
 [21] macro expansion
    @ C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:278 [inlined]
 [22] macro expansion
    @ C:\Users\USER\.julia\packages\ProgressMeter\Vf8un\src\ProgressMeter.jl:940 [inlined]
 [23] render(video::Video; framerate::Int64, pathname::String, liveview::Bool, streamconfig::Nothing, tempdirectory::String, ffmpeg_loglevel::String)
    @ Javis C:\Users\USER\.julia\packages\Javis\FLdWO\src\Javis.jl:277
 [24] top-level scope
    @ C:\Users\USER\Documents\Fysiikka\latex.jl:28`
```

**Additional context**
I should add that the rest of Javis seems to be working fine, only the LaTeX support doesn't work. Also, this problem seems to persist when trying to use 'run' from REPL, so problem might be that my Julia install is somehow configured.

Decided to post this as an issue anyway, because Javis depends on tex2svg, and I just did a clean Julia, npm and Javis install from scratch. So doing this the obvious way didn't lead to a working Javis for me.

If anyone has any ideas, greatly appreciated :)

**Comment by Wikunia** [comment]
Thanks for opening the issue. If I understand your additional context correctly running `tex2svg` from the Julia command line also doesn't work? Then I suppose it is kind of a path problem. I'll ask around if anyone can replicate this using windows as I don't have a machine to test this on.

**Comment by arunningcroc** [comment]
> 
> 
> Thanks for opening the issue. If I understand your additional context correctly running `tex2svg` from the Julia command line also doesn't work? Then I suppose it is kind of a path problem. I'll ask around if anyone can replicate this using windows as I don't have a machine to test this on.

Yeah, that's right. I don't understand why, though, as the relevant np dir is in both the system and user path variables, so it should work. It does work correctly in powershell.

**Comment by arunningcroc** [comment]
Some additional info: I can run other programs, like say git, from Julia REPL with run or open. Git is in the path variable in exactly same way as the node modules.

**Comment by Wikunia** [comment]
Do you mind running `Sys.which("tex2svg")` in Julia and post the result here?

**Comment by arunningcroc** [comment]
Doesn't give anything in return, empty string. By contrast, e.g. Sys.which("git") does give the right path. Powershell's Get-Command tex2svg returns "C:\Users\USER\AppData\Roaming\npm\tex2svg.ps1", which is what I'd expect.

**Comment by arunningcroc** [comment]
Actually, I just noticed something interesting. Doing run(`tex2svg.cmd`) or Sys.which("tex2svg.cmd") actually works. Doing run(`tex2svg.ps1`) doesn't, but it does find tex2svg.ps1, so probably it's a matter of not spawning a powershell process. Basically, tex2svg doesn't work because run and open don't spawn any process capable of handling those files on Windows. Even if I have set a default program for .ps1 files, for instance, run and open don't open the relevant process for handling those files.

If I simply change latex.jl in the sources to instead of tex2svg just call tex2svg.cmd, that produces a different error: this time, there's supposedly no \end{equation}: 

`TeX parse error: Missing \end{equation}
Entity: line 1: parser error : Document is empty

^
ERROR: LoadError: LightXML.XMLParseError{String}("Failure in parsing an XML file.")
Stacktrace: `

Anyway it's probably not ideal to have to change the sources like this to work on Windows.

**Comment by TheCedarPrince** [comment]
Hey @arunningcroc - just to give you a heads-up, we are actively trying to pinpoint the problem but as @Wikunia and I do not have  access to computers running Windows, a friend (thanks so much @Ved-Mahajan !) is helping us track down what this issue is on their Windows computer. As of now, it is interesting to note that up until now, Windows has not had this problem with Javis that we are aware of. Stay tuned for updates!

**Comment by arunningcroc** [comment]
Any progress? I could make none :)

**Comment by Wikunia** [comment]
Does the solution described in #420 help?

**Comment by arunningcroc** [comment]
@Wikunia It produces the same Tex parsing error as my solution of changing "tex2svg" to "tex2svg.cmd", the one I described in  [this comment.](https://github.com/Wikunia/Javis.jl/issues/384#issuecomment-894672045) In fact, I think that solution and #420 do the exact same thing, as Windows knows to spawn a cmd process when confronted with a .cmd file.

What I didn't notice before, though, is that only the tutorial seems to be failing for me, it produces the tex parser error above. But if I try with some other Latex, like:

`\begin{bmatrix}0 & 1 \\ 1 & 0\end{bmatrix}`

it seems to work just fine, which I completely missed previously. So kudos to @gpucce for making me try this again. I'll ask @gpucce in #420 if they can get the tutorial working.

**Comment by Wikunia** [comment]
Yeah it seems to me that the windows version has some problems with multiline?

**Comment by Wikunia** [comment]
Can you verify this when using the multiline string from the tutorial inside `L"""..."""` and put it into a single line `L".."?

**Comment by gpucce** [comment]
I was trying to fix and the one line solution together with the `cmd /C tex2svg` switch does fix it for me

**Comment by Wikunia** [comment]
Awesome yeah then we probably just need a split on new line and a join to make it one line and check whether it's a Windows system. Wanna make the PR @gpucce ?

**Comment by arunningcroc** [comment]
@Wikunia Yep, one line does the trick.. but I am curious about the reason why Windows doesn't like multiline strings in this instance. I tested a few things, including attempting to spawn a powershell and changing line endings from CRLF to LF, but no luck.

Guess it's a waste of time to wonder about that given the easy solution.

**Comment by Wikunia** [comment]
I also have no clue about that but if we can workaround that I'm already quite happy to be honest 😊

**Comment by gpucce** [comment]
I think it works at least for tutorial 4 it does I can make the PR though I don't know if there are tests for the latex part

**Comment by Wikunia** [comment]
There aren't yet for that part but a PR would be awesome then I can test it on Linux whether it destroys something. ☺️

**Comment by gpucce** [comment]
On it way!
