### ISSUE TITLE
update Contributors 

### ISSUE THREAD

**Issue by Wikunia** [Wikunia/Javis.jl#391]
We forgot to put @rmsrosa into the contributors list. He provided the vortex example: #389

**Comment by Wikunia** [comment]
Documenter gets run now on GitHub I meant for the section at the end of the readme.

**Comment by rmsrosa** [comment]
Oh, ok. So maybe it just needs some time to build. I checked the example section and the vortex one was not there yet.

**Comment by Wikunia** [comment]
Now in the dev version:
https://wikunia.github.io/Javis.jl/dev/examples/
We'll tag a new release after #390 gets merged and then it will be in stable :wink:
