### ISSUE TITLE
Add option to reverse animation

### ISSUE THREAD

**Issue by gpucce** [Wikunia/Javis.jl#419]
**Is your feature request related to a problem? Please explain.**
I don't know if I can't find it, but it looks like there is no easy way to reverse an animation

**Describe the solution you'd like**
Maybe one could add an argument to the render function so it is changes from 
```
function render(
    video::Video;
    framerate = 30,
    pathname = "javis_$(randstring(7)).gif",
    liveview = false,
    streamconfig::Union{StreamConfig,Nothing} = nothing,
    tempdirectory = "",
    ffmpeg_loglevel = "panic",
    rescale_factor = 1.0,
)
    layers = video.layers
    objects = video.objects
    frames = preprocess_frames!(video)
```
to
```julia
function render(
    video::Video;
    framerate = 30,
    pathname = "javis_$(randstring(7)).gif",
    liveview = false,
    streamconfig::Union{StreamConfig,Nothing} = nothing,
    tempdirectory = "",
    ffmpeg_loglevel = "panic",
    rescale_factor = 1.0,
    reverse_animation = false
)
    layers = video.layers
    objects = video.objects
    frames = preprocess_frames!(video)
    if reverse_animation 
        frames = reverse(frames)
    end
```

**Describe alternatives you've considered**
One could also create a `reverse_render` function, I have no clue which is better.

I can make the PR if it makes sense.

**Comment by Wikunia** [comment]
Thanks for opening the issue! Do you mind giving an example of when this might be useful? I think the fix you described will not work that easy especially with morphing (which is undocumented yet sry) For other cases I'm not actually sure whether this will work.

**Comment by gpucce** [comment]
From a serioues perspective I believe it could be useful to show some concepts like irreversibility of time or similar in physics (maybe). On a funnier notice some animations are really nice when seen back and forth.  Also it could be an utility in some cases, for example together with a `simmetrize` one could do butterfly like animations very easily (I might be loosing the point).

An example of how back and forth can be nice!!
![boolean_point_process](https://user-images.githubusercontent.com/32967787/133306983-cffce4ec-3bb4-4047-9adf-c94b3d24ea4e.gif)

**Comment by Wikunia** [comment]
Thanks I was thinking about the back and forth part as well but I think for that we should integrate it directly and just copy the images of forward reverse their numbering and render all of that together. Otherwise you would have two gifs that you would need to combine, right? And that way we only need to compute it ones

**Comment by gpucce** [comment]
yeah this is done with 
```
if reverse_animation
    frames = [frames; reverse(frames)]
end
```
But as you said here I use no action it is entirely done by hand so it might not integrate well with the actions

**Comment by gpucce** [comment]
More in general though it might be nice to have a way to externall perform Luxor.like function on all frames so smth like before render(video...) one calls revers(video) and gets it reversed when it is rendered so one could then similarly implement simmetrize left/right/up/down or also crop in some sense and all kinds of things that make sense for all frames at once. Don't know how much sense it makes.

**Comment by Wikunia** [comment]
Yeah I would maybe have a function which applies a function on the frames inside the tempdirectory.
