### ISSUE TITLE
[BUG] Hard to render latex on windows

### ISSUE THREAD

**Issue by gpucce** [Wikunia/Javis.jl#420]
**Describe the bug**

Trying to render latex on windows is difficult, I don't exactly know how it works, but reading the first note on julia docs [page](https://docs.julialang.org/en/v1/manual/running-external-programs/#Running-External-Programs) about running external programs I could find a work around. In 

```julia
function get_latex_svg(text::LaTeXString)
    # check if it's cached
    if haskey(LaTeXSVG, text)
        svg = LaTeXSVG[text]
    else
        ts = strip_eq(text)
        command = `tex2svg $ts`
        try
            svg = read(command, String)
        catch e
            @warn "Using LaTeX needs the program `tex2svg` which might not be installed"
            @info "It can be installed using `npm install -g mathjax-node-cli`"
            throw(e)
        end
        LaTeXSVG[text] = svg
    end
    return svg
end
```
I switched \`tex2svg $ts\` to \`cmd /C tex2svg $ts\` and it works. I don't know the way to implement it properly.

**To Reproduce**

On a windows machine running julia downloaded from Microsoft Store try to rendere any latex even with mathjax-node-cli installed

1. Julia Version (i.e. output of `julia -v`):
1.6.2

2. Operating system (Mac, Linux, Windows):
Windows 10

3. Javis version (i.e output of `] status Javis` in the REPL) 
Javis#master

**Comment by Wikunia** [comment]
A great thanks for the included fix idea. I assume you just need the first thing in https://docs.julialang.org/en/v1/manual/handling-operating-system-variation/ so `Sys.iswindows` and then call the fix with `cmd /C` and otherwise (for Linux and Mac) `tex2svg`

**Comment by arunningcroc** [comment]
Hey @gpucce , I ran in to a similar issue in #384 and found a very similar solution as you did, but the tutorial latex still doesn't render for me. Do you get that LaTeX to render properly? I mean [this tutorial](https://wikunia.github.io/Javis.jl/stable/tutorials/tutorial_4/).
