### ISSUE TITLE
add a text function 

### ISSUE THREAD

**Issue by xiaodaigh** [Wikunia/Javis.jl#51]
for printing text on screen like a line.

`text("text", font=DEFAULT_FONT)`

**Comment by Wikunia** [comment]
Would this be different than https://juliagraphics.github.io/Luxor.jl/v0.11/text.html?

Or do you want to specify the font directly in the command? I would imagine that the font doesn't change often enough to make this reasonable.

**Comment by TheCedarPrince** [comment]
This came from a live stream today with @xiaodaigh asking about how one can display text on screen. Not `LaTeX` rendering, just standard text. Do you know how to add this functionality @Wikunia ? It would be really cool if we could make the default text be the [JuliaMono Font](https://github.com/cormullion/juliamono)

**Comment by xiaodaigh** [comment]
Same as luxor is OK. So it already works

**Comment by Wikunia** [comment]
I don't think that this is what the user wants as a default @TheCedarPrince 
Additionally I don't want to install fonts. The default is Luxor should be fine and can be changed easily in the background action if needed.
