### ISSUE TITLE
Add Javis to General Julia Registry

### ISSUE THREAD

**Issue by TheCedarPrince** [Wikunia/Javis.jl#52]
We need to add Javis to the General Julia Registry for the initial release! Do you know what all is involved with getting it added to the registry @Wikunia ?

**Comment by Wikunia** [comment]
It's one command as we havehttps://github.com/Wikunia/Javis.jl/blob/master/.github/workflows/TagBot.yml installed.
I'll handle it once we finished the milestone.

**Comment by TheCedarPrince** [comment]
All yours @Wikunia ! I can't do this -- only you can. :smile:

**Comment by Wikunia** [comment]
@JuliaRegistrator register
