### ISSUE TITLE
ffmpeg not installed by default on windows

### ISSUE THREAD

**Issue by xiaodaigh** [Wikunia/Javis.jl#53]
So I can't use javis which is calling ffmpeg.

I had to install it and set my path. 99% of users won't know how to do it.

Perhaps binarybuilder.jl can help?

I want to help but I may not get to it soon enough.

**Comment by Wikunia** [comment]
I have no real clue how this stuff works. Do you reckon using https://github.com/JuliaIO/FFMPEG.jl might be enough?

**Comment by xiaodaigh** [comment]
thta could work. u just need to add it as a dependency and call `FFMPEG.exe("-version")` instead of `run`

**Comment by Wikunia** [comment]
I'll try it out and ping you in a PR then such that you can try it on windows. Thanks for the issue!

**Comment by xiaodaigh** [comment]
seems to be working in the pr

**Comment by Wikunia** [comment]
Thanks for testing!
