### ISSUE TITLE
Usage of VideoIO

### ISSUE THREAD

**Issue by Wikunia** [Wikunia/Javis.jl#55]
We probably want to make it possible to create `mp4` videos easily and not just `gif`.
Not sure how VideoIO works but it might be even faster as we don't need to write each frame to a file.

**Comment by TheCedarPrince** [comment]
Take each frame, store it into an image array, and then somehow directly save it to an `mp4`. If possible, create an `mp4` file first from which we can continuously dump `frames` into.
