### ISSUE TITLE
ProgressMeter

### ISSUE THREAD

**Issue by Wikunia** [Wikunia/Javis.jl#56]
For longer animations it might be useful to provide a progress bar. 
No user should ask: "Is it doing something or is it hanging?"

https://github.com/timholy/ProgressMeter.jl

**Comment by Wikunia** [comment]
What do you think about a milestone of v0.2.0 for this @TheCedarPrince ?

**Comment by TheCedarPrince** [comment]
I like this a lot! I added it to v0.2.0. My only question about be about how to incorporate this with FFMPEG. Are you thinking about exploring adding this functionality or would you like me to try taking it on for the next milestone?

**Comment by Wikunia** [comment]
I would only use it for creating every frame. Thus should be the slow part. I think ffmpeg is relatively fast in creating a gif or mp4.
This should be fairly easy to implement but I would say: let's finish the important stuff for v0.1 first
