### ISSUE TITLE
Better defaults for kwargs in javis

### ISSUE THREAD

**Issue by Wikunia** [Wikunia/Javis.jl#57]
Currently the defaults for `tempdirectory`, `deletetemp`, ... are all not the best :smile: 

I think `tempdirectory` should be https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.tempdir or maybe `mktempdir`

- `pathname = javid_randomstring.gif`

I would remove `creategif` and just create a `gif` if pathname is not empty. This makes it easy to later set `pathname` to `filename.mp4` to create a video and possibly we can also remove `deletetemp`. :wink: 

The bug label is coming from this error message:
```
IOError: could not spawn `rm -rf .`: no such file or directory (ENOENT)
```
mentioned in slack when using `deletetemp`

**Comment by TheCedarPrince** [comment]
Really like this idea. I approved it over in #58
