### ISSUE TITLE
Access to arbitrary return

### ISSUE THREAD

**Issue by Wikunia** [Wikunia/Javis.jl#62]
If a drawing function returns something other than a `Point` or a `Transformation` the user currently can't access it easily.
We might want to have a function `val` for that.
Such that 
```
function ret(args...)
   return "Bla"
end
```

```
Action(1:100, :test, ret)
Action(1:100, (args...)->text(val(:test))
```

works

**Comment by TheCedarPrince** [comment]
I really like this idea. Let me know if you want me to test this out at some point when ready. I will add it into the tutorials when it is ready to go. #25
