### ISSUE TITLE
Javis Templates

### ISSUE THREAD

**Issue by TheCedarPrince** [Wikunia/Javis.jl#64]
Hey @Wikunia ,

This is an idea I have been thinking about for a bit and I wanted to write it down before I forgot. I am not sure how difficult the idea would be to implement or if it would be wise to implement it in another repository but I think common animations made using `Javis` should be offered as templates. This thought spawned off from animation of an 10-20 Electrode EEG Array I made:

![eeg](https://user-images.githubusercontent.com/29561456/89726579-eb821680-d9e9-11ea-83f9-275e5e9bfa88.gif)

The code to make this, though easy to make, took several hours to make and over a hundred lines of code. I would love to provide a method that `Javis` could provide which enables a user to load a template that we have curated. Perhaps in the form of something like this `Action(:same, :eeg_array, load_template("eeg_array"))` that returns a list of actions needed to make the basic template of the array (i.e. minus the colors).

This is an idea that I don't know how easy it is to implement but I think would be of great benefit for future users. Plus, it would be cool if we could open it up for users to add in their own templates for other users.

If you think it makes sense, I'd be happy to sink some time into this maybe for v0.2.0 or even v0.3.0 (dreaming big here!) as I would certainly like this functionality.

Thoughts?

**Comment by Wikunia** [comment]
Can you clarify what this should do?
How would the user have access to the circles to update the color?
Wouldn't it be the easiest to write a function `eeg_array` which takes in a function and an update rate?
And then calls the function whenever `frame % update_rate == 0`. The function itself returns the current color for each circle and then the colors get updated?

If you really want the list of actions you could also return the list of actions and then call 
```
javis(video, [
   eeg_actions()...
])
```

**Comment by TheCedarPrince** [comment]
Hey @Wikunia,

Accessing the circles was something I was thinking about as well. Thinking about that beyond just this example, I cannot think of an easy way to manipulate animations that would be loaded as a template. In fact, I don't think we'd even want to support modifying templates in the way you are describing (e.g. writing a function that someone could import).

Rather, what may be of more utility is to perhaps make a separate repository called something like `JavisTemplates` which contains source code for commonly used animations. People than can take these animations and modify them to suit their purposes.

I think supporting each template's own unique behavior would be too much to worry about and outside the scope of the main `Javis` project. Do you think that may be a good solution to this idea?

**Comment by Wikunia** [comment]
I think in general having an examples folder repository for these is a good idea. I would still consider writing the eeg code as a function which takes in a list of colors or even a function as an input just to show that possibility. Additionally this currently does not show special behavior of Javis if I saw it correctly and can be done easily with Luxor as you don't seem to use `Transitions` nor the ids you create but never use :smile:  as you don't save anything in it.

**Comment by TheCedarPrince** [comment]
Gotcha! Then I think I will work on making a repository for templates (I'll put that in for milestone v0.2.0) - do you want to make it on your GitHub or should I make it on mine?

Ah - then I will work on that particular idea for making an eeg function for Javis to show that functionality. I'll reference this functionality for #50

**Comment by Wikunia** [comment]
Feel free to open it with your account.
