### ISSUE TITLE
Auto-Export of Luxor Functions

### ISSUE THREAD

**Issue by TheCedarPrince** [Wikunia/Javis.jl#70]
Based on conversation with @Wikunia , the manual importing of `Luxor` is somewhat of a pain for each file written using Javis. @thofma suggested a great idea based on [Hecke.jl](https://github.com/thofma/Hecke.jl/blob/da91ba6cd304e4399a272931b022d5d94cb407b2/src/Hecke.jl#L82) to auto-export each function in Luxor automatically within Javis. Let's get this implemented for documentation and for #44 .

**Comment by thofma** [comment]
If you are not afraid of additional dependencies, you could also use the Reexport.jl package like here: https://github.com/SciML/DifferentialEquations.jl/blob/master/src/DifferentialEquations.jl

**Comment by Wikunia** [comment]
Yeah we kinda thought it's not necessary as you mentioned and we have more control over some behavior of exporting only some functions and overwriting others I guess.
