### ISSUE TITLE
Allow user to write loop over frames himself by providing a single frame render Javis like function

### ISSUE THREAD

**Issue by freemin7** [Wikunia/Javis.jl#92]
Currently Javis processes a set of actions over a certain set of frames. However for certain applications it might be preferable to give the user control over rendering loop if he wants to write into several files in parallel and it might help with consistent frame rates for live streaming too.

A Javis would be called and return after preparing/rendering a single/(fixed number of) frame. It would preferable if it also kept all the framebuffers etc allocated not unlike Integrator Interface from the DiffEq eco system. ( https://diffeq.sciml.ai/release-5.0/basics/integrator.html )

**Comment by Wikunia** [comment]
Can you give an example on how one would use this functionality and why?
Is the problem mostly that Javis is kinda slow atm? Then #102 might solve this.

**Comment by freemin7** [comment]
This could also be accomplished by providing the user a function (or parameter into the javis call) to render a certain frame of an animation.
This might be easier to implement, although it would occur all constant overhead that Javis has once per frame. I don't guess that will be a problem though.

**Comment by TheCedarPrince** [comment]
Hey @freemin7 , I think you will have this functionality in PR #138 in the function `get_javis_frame` in v0.2.0. Let us know if that works for you!

**Comment by TheCedarPrince** [comment]
We need to add a preprocess functionality such that a particular frame can be retrieved without having to preprocess all frames.

**Comment by Wikunia** [comment]
Can this be closed as we have a preprocess function now?

**Comment by TheCedarPrince** [comment]
Ping @freemin7 that this functionality has been added in v0.3.0 of Javis.

Closed! :smile:

**Comment by freemin7** [comment]
Is there already some doc for it?

**Comment by Wikunia** [comment]
It's not exported @freemin7 but you can have a look at the docstring with `? Javis.preprocess_frames!`

It basically computes the actual frames for each `Object` and `Action`.
