### ISSUE TITLE
Animation persist after completion

### ISSUE THREAD

**Issue by TheCedarPrince** [Wikunia/Javis.jl#97]
**Is your feature request related to a problem? Please explain.**

I was experimenting with `BackgroundAction` syntax and I was thinking it might be a good idea to extend `SubAction` syntax to `BackgroundAction`'s. Especially for the functions `draw_grid` and `zero_lines`.

If that is the case, it might make sense to have `BackgroundAction` only have access to functions like `draw_grid` and `zero_lines` and not as a general `Action`.

**Describe the solution you'd like**

What I would love to see as a user interface would be something like this:

```julia
              BackgroundAction(1:180, ground), subactions = [
                 SubAction(1:60, draw_grid()),                                                    
                 SubAction(1:60, zero_lines())
                 ]
```

Also, I am not sure if this should be a separate issue, but I would like to see the grid lines persist after their initial animation such that I could draw on top of them later.

**Describe alternatives you've considered**

Currently, this would be the way to invoke this functionality:

```julia
               BackgroundAction(1:180, ground),                                        
               Action(1:60, draw_grid()),                                                    
               Action(1:60, zero_lines()),
```

**Comment by Wikunia** [comment]
Yeah in the latter case the lines would not be persistent.
I was actually thinking about having something like
```
 BackgroundAction(1:180, ground),      
Action(1:180, draw_grid; subactions=[
    SubAction(1:60, appear(:lr, :tb))
])
```

where appear can take some arguments like here `:lr` left -> right and `:tb` for top -> bottom and then this gets saved in the parent `Action`  options or something such that the `draw_grid` function knows how to handle that :D 
Then `Action(1:60, draw_grid)` might simply draw the grid for that many frames without any animation?

**Comment by Wikunia** [comment]
Also see #100

**Comment by Wikunia** [comment]
I think I would handle this inside the draw grid one #38 and move this out of this milestone? What do you think about it @TheCedarPrince ?
