### ISSUE TITLE
Hijack Plotting Library for Object Positioning

### ISSUE THREAD

**Issue by TheCedarPrince** [Wikunia/Javis.jl#98]
**Is your feature request related to a problem? Please explain.**

I have been thinking a lot about drawing vectors (#31) using `Javis`. I realized that if I were to draw a vector, it would not be related to any other objects being plotted. Furthermore, I would essentially be replicating a limited plotting library. I would much rather like to hijack an already existing plotting lib such as `Gadfly.jl` or `Plots.jl` to handle the generation of points or such for a plot.

What do you think @Wikunia ?

**Describe the solution you'd like**

I think that `Gadfly.jl` would be the best to go with as it handles `svg` and has a focus on interop.

**Comment by Wikunia** [comment]
Can you elaborate a bit more? I was wondering whether we can simply define the size of a layer by scaling in such a way that we have coordinates that fit when working with anything one wants to draw in different coordinate system.
Maybe you mean something completely different though. 

I would still like to have full control over anything the user wants to plot and I don't think that works when interacting with a plotting library. We also don't want to have full plotting library support I reckon?

**Comment by TheCedarPrince** [comment]
This issue was effectively addressed by #412 See conversation there for details.
